def GetFiles(val):
    if val == "Char 2K":
        ret = [
            "3DCHARS/Amz.mmp",
            "3DCHARS/Bar.mmp",
            "3DCHARS/dwf.mmp",
            "3DCHARS/Kgt.mmp",
        ]
    elif val == "Char 2K Hybrid":
        ret = [
            "3DCHARS/Amz.mmp",
            "3DCHARS/Bar.mmp",
            "3DCHARS/dwf.mmp",
            "3DCHARS/Kgt.mmp",
        ]
    elif val == "Char 2K Original":
        ret = [
            "3DCHARS/Amz.mmp",
            "3DCHARS/Bar.mmp",
            "3DCHARS/dwf.mmp",
            "3DCHARS/Kgt.mmp",
            "3DCHARS/ork.mmp",
        ]
    elif val == "HUD":
        ret = [
            "DATA/Vida enemigo 8_hi.png",
            "DATA/Vida enemigo_hi.png",
            "DATA/Vida_hi.png",
            "DATA/mmps/FLECHAENEMIGODERECHA_hi.png",
            "DATA/mmps/FLECHAENEMIGOIZQUIERDA_hi.png",
            "DATA/mmps/MARCADORATAQUE_hi.png",
            "DATA/mmps/MARCADORDEFENSA_hi.png",
            "DATA/mmps/MARCADORLANZAMAGOTAM_hi.png",
            "DATA/mmps/MARCADORVIDARED_hi.png",
            "DATA/mmps/MARCADORVIDAYXP_hi.png",
            "DATA/mmps/MARCOINVENTARIO_hi.png",
            "DATA/mmps/SELECTORENEMIGO_hi.png",
        ]
    elif val == "GamePlay Enhancements":
        ret = [
            "LIB/Actions.py",
            "LIB/Basic_Funcs.py",
            "LIB/GenFX.py",
            "LIB/PowDefWidgets.py",
            "LIB/Scorer.py",
        ]
    elif val == "Reshade":
        ret = [
            "bin/bin/ReShade.ini",
            #
            "bin/bin/Preset/Forge of Xshathra.ini",
            "bin/bin/Preset/Fortress of Nemrut.ini",
            "bin/bin/Preset/Fortress of Tell Halaf.ini",
            "bin/bin/Preset/Island of Karum.ini",
            "bin/bin/Preset/Kashgar (Barbarian 1st level).ini",
            "bin/bin/Preset/Kazel Zalam (Dwarf 1st level).ini",
            "bin/bin/Preset/Marakamda (Amazon 1st level).ini",
            "bin/bin/Preset/Mines of Kelbegen.ini",
            "bin/bin/Preset/Oasis of Nejeb.ini",
            # "bin/bin/Preset/ReShadePreset.ini",
            "bin/bin/Preset/Shalatuwar Fortress.ini",
            "bin/bin/Preset/Start character selection.ini",
            "bin/bin/Preset/Tabriz (knight 1st level).ini",
            "bin/bin/Preset/Temple of Al Farum.ini",
            "bin/bin/Preset/Temple of Ianna.ini",
            "bin/bin/Preset/The Abyss.ini",
            "bin/bin/Preset/Tombs of Ephyra.ini",
            "bin/bin/Preset/Tower of Dal Gurak.ini",
            # "bin/bin/B_Reshade.addon",
            #
            "bin/bin/reshade-shaders/Shaders/Daltonize.fx",
            "bin/bin/reshade-shaders/Shaders/Deband.fx",
            "bin/bin/reshade-shaders/Shaders/DisplayDepth.fx",
            "bin/bin/reshade-shaders/Shaders/EyeAdaption.fx",
            "bin/bin/reshade-shaders/Shaders/FakeHDR.fx",
            "bin/bin/reshade-shaders/Shaders/FocalDOF.fx",
            "bin/bin/reshade-shaders/Shaders/LightDoF.fx",
            "bin/bin/reshade-shaders/Shaders/LUT.fx",
            "bin/bin/reshade-shaders/Shaders/MagicHDR.fx",
            "bin/bin/reshade-shaders/Shaders/Technicolor.fx",
            "bin/bin/reshade-shaders/Shaders/UIMask.fx",
            "bin/bin/reshade-shaders/Shaders/DrawText.fxh",
            "bin/bin/reshade-shaders/Shaders/FXAA.fxh",
            "bin/bin/reshade-shaders/Shaders/KeyCodes.fxh",
            "bin/bin/reshade-shaders/Shaders/Macros.fxh",
            "bin/bin/reshade-shaders/Shaders/ReShade.fxh",
            "bin/bin/reshade-shaders/Shaders/ReShadeUI.fxh",
            "bin/bin/reshade-shaders/Shaders/SMAA.fxh",
            "bin/bin/reshade-shaders/Shaders/TriDither.fxh",
            "bin/bin/reshade-shaders/Shaders/UIDetect.fxh",
            "bin/bin/reshade-shaders/Shaders/VRS_Map.fxh",
            #
            "bin/bin/reshade-shaders/Shaders/qUINT/qUINT_bloom.fx",
            "bin/bin/reshade-shaders/Shaders/qUINT/qUINT_dof.fx",
            "bin/bin/reshade-shaders/Shaders/qUINT/qUINT_mxao.fx",
            "bin/bin/reshade-shaders/Shaders/qUINT/qUINT_ssr.fx",
            "bin/bin/reshade-shaders/Shaders/qUINT/qUINT_common.fxh",
            #
            "bin/bin/reshade-shaders/Shaders/FXShaders/API.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/AspectRatio.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Blending.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Canvas.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Common.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Convolution.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Digits.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Dithering.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/KeyCodes.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Math.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Tonemap.fxh",
            "bin/bin/reshade-shaders/Shaders/FXShaders/Transform.fxh",
            #
            # "bin/bin/reshade-shaders/Textures/dummy",
            # "bin/bin/reshade-shaders/Textures/Layer.png",
            # "bin/bin/reshade-shaders/Textures/LensDB.png",
            # "bin/bin/reshade-shaders/Textures/LensDB2.png",
            # "bin/bin/reshade-shaders/Textures/LensDOV.png",
            # "bin/bin/reshade-shaders/Textures/LensDUV.png",
            # "bin/bin/reshade-shaders/Textures/LensSprite.png",
            # "bin/bin/reshade-shaders/Textures/lut.png",
            # "bin/bin/reshade-shaders/Textures/MagicBloom_Dirt.png",
            # "bin/bin/reshade-shaders/Textures/MatCap.png",
            # "bin/bin/reshade-shaders/Textures/monochrome_gaussnoise.png",
            # "bin/bin/reshade-shaders/Textures/MultiLut_atlas1.png",
            # "bin/bin/reshade-shaders/Textures/NeoBloom_LensDirt.png",
            # "bin/bin/reshade-shaders/Textures/neutral_lut.png",
            # "bin/bin/reshade-shaders/Textures/NormalMap.png",
            # "bin/bin/reshade-shaders/Textures/Overlay.png",
            # "bin/bin/reshade-shaders/Textures/UIDetectMaskRGB.png",
            # "bin/bin/reshade-shaders/Textures/UIMask.png",
        ]
    elif val == "Texture":
        ret = [
            # .mmp
            "3DCHARS/Actors.mmp",
            "3DCHARS/actors_javi.mmp",
            "3DCHARS/Amzskin1.mmp",
            "3DCHARS/Amzskin2.mmp",
            "3DCHARS/Barskin1.mmp",
            "3DCHARS/Barskin2.mmp",
            "3DCHARS/Chk.mmp",
            "3DCHARS/cosita.mmp",
            "3DCHARS/DalGurak.mmp",
            "3DCHARS/DarkKnight.mmp",
            "3DCHARS/darklord.mmp",
            "3DCHARS/Dork.mmp",
            "3DCHARS/Dwfskin1.mmp",
            "3DCHARS/Dwfskin2.mmp",
            "3DCHARS/enanos.mmp",
            "3DCHARS/Gdemon.mmp",
            "3DCHARS/Glm_cl.mmp",
            "3DCHARS/Glm_ic.mmp",
            "3DCHARS/Glm_lv.mmp",
            "3DCHARS/Glm_mt.mmp",
            "3DCHARS/Glm_st.mmp",
            "3DCHARS/Gok.mmp",
            "3DCHARS/Kgtskin1.mmp",
            "3DCHARS/Kgtskin2.mmp",
            "3DCHARS/lch.mmp",
            "3DCHARS/Ldm.mmp",
            "3DCHARS/min.mmp",
            "3DCHARS/NPK.mmp",
            "3DCHARS/Org.mmp",
            "3DCHARS/ork.mmp",
            "3DCHARS/rgn.mmp",
            "3DCHARS/roturas.mmp",
            "3DCHARS/Skl.mmp",
            "3DCHARS/spd.mmp",
            "3DCHARS/TKN.mmp",
            "3DCHARS/trl_dk.mmp",
            "3DCHARS/Vmp.mmp",
            "3DCHARS/zkn.mmp",
            "3dobjs/3dObjs.mmp",
            "3dobjs/bolarayos.mmp",
            "3dobjs/CilindroMagico.mmp",
            "3dobjs/CilindroMagico2.mmp",
            "3dobjs/CilindroMagico3.mmp",
            "3dobjs/conos.mmp",
            "3dobjs/dalblade.mmp",
            "3dobjs/esferagemaazul.mmp",
            "3dobjs/esferagemaroja.mmp",
            "3dobjs/esferagemaverde.mmp",
            "3dobjs/esferanegra.mmp",
            "3dobjs/esferaorbital.mmp",
            "3dobjs/espectro.mmp",
            "3dobjs/firering.mmp",
            "3dobjs/genericos.mmp",
            "3dobjs/luzdivina.mmp",
            "3dobjs/magicshield.mmp",
            "3dobjs/nube.mmp",
            "3dobjs/objetos_p.mmp",
            "3dobjs/ondaexpansiva.mmp",
            "3dobjs/Pfern.mmp",
            "3dobjs/pmiguel.mmp",
            "3dobjs/telaranya.mmp",
            "3dobjs/vortice.mmp",
            "3dobjs/weapons.mmp",
            "Maps/Barb_M1/barb.mmp",
            "Maps/Barb_M1/barb_d.mmp",
            "Maps/Barb_M1/NOBJS.mmp",
            "Maps/Barb_M1/objetos_p.mmp",
            "Maps/Barb_M1/Skl.mmp",
            "Maps/Btomb_M12/btomb.mmp",
            "Maps/Btomb_M12/btomb_d.mmp",
            "Maps/Btomb_M12/NOBJS.mmp",
            "Maps/Btomb_M12/Skl.mmp",
            "Maps/Casa/casa.mmp",
            "Maps/Casa/casa_d.mmp",
            "Maps/Casa/seleccion.mmp",
            "Maps/Chaos_M17/chaos.mmp",
            "Maps/Chaos_M17/chaos_d.mmp",
            "Maps/Chaos_M17/Skl.mmp",
            "Maps/Desert_M13/desert.mmp",
            "Maps/Desert_M13/desert_d.mmp",
            "Maps/Desert_M13/NOBJS.mmp",
            "Maps/Desert_M13/Skl.mmp",
            "Maps/Dwarf_M3/dwarf.mmp",
            "Maps/Dwarf_M3/dwarf_d.mmp",
            "Maps/Dwarf_M3/NOBJS.mmp",
            "Maps/Dwarf_M3/Skl.mmp",
            "Maps/Ice_M11/ice.mmp",
            "Maps/Ice_M11/ice_d.mmp",
            "Maps/Ice_M11/NOBJS.mmp",
            "Maps/Ice_M11/Skl.mmp",
            "Maps/Ice_M11/vid.mmp",
            "Maps/Island_M8/acido2.mmp",
            "Maps/Island_M8/island.mmp",
            "Maps/Island_M8/island_d.mmp",
            "Maps/Island_M8/lava_128.mmp",
            "Maps/Island_M8/NOBJS.mmp",
            "Maps/Island_M8/Skl.mmp",
            "Maps/Labyrinth_M6/bloquepi.mmp",
            "Maps/Labyrinth_M6/LABYR.MMP",
            "Maps/Labyrinth_M6/NOBJS.mmp",
            "Maps/Labyrinth_M6/pulruna.mmp",
            "Maps/Mine_M5/acido.mmp",
            "Maps/Mine_M5/mine.mmp",
            "Maps/Mine_M5/mine_d.mmp",
            "Maps/Mine_M5/NOBJS.mmp",
            "Maps/Orc_M9/NOBJS.mmp",
            "Maps/Orc_M9/orcst.mmp",
            "Maps/Orc_M9/orcst_d.mmp",
            "Maps/Palace_M15/Adoquinruna.mmp",
            "Maps/Palace_M15/NOBJS.mmp",
            "Maps/Palace_M15/palace.mmp",
            "Maps/Palace_M15/palace_d.mmp",
            "Maps/Ragnar_M2/NOBJS.mmp",
            "Maps/Ragnar_M2/ragnar.mmp",
            "Maps/Ragnar_M2/ragnar_d.mmp",
            "Maps/Ruins_M4/barramaya.mmp",
            "Maps/Ruins_M4/dome.mmp",
            "Maps/Ruins_M4/piedras.mmp",
            "Maps/Ruins_M4/ruins.mmp",
            "Maps/Tomb_M7/NOBJS.mmp",
            "Maps/Tomb_M7/objetos_p.mmp",
            "Maps/Tomb_M7/Skl.mmp",
            "Maps/Tomb_M7/tomb.mmp",
            "Maps/Tomb_M7/tomb_d.mmp",
            "Maps/Tower_M16/acido.mmp",
            "Maps/Tower_M16/actors_javi.mmp",
            "Maps/Tower_M16/lava_128.mmp",
            "Maps/Tower_M16/NOBJS.mmp",
            "Maps/Tower_M16/pmiguel.mmp",
            "Maps/Tower_M16/Skl.mmp",
            "Maps/Tower_M16/tower.mmp",
            "Maps/Tower_M16/tower_d.mmp",
            "Maps/Tower_M16/vid.mmp",
            "Maps/Volcano_M14/lava_128.mmp",
            "Maps/Volcano_M14/NOBJS.mmp",
            "Maps/Volcano_M14/volcano.mmp",
            "Maps/Volcano_M14/volcan_d.mmp",
            # .bod
            "3DCHARS/Kgt_L.BOD",
            # .jpg
            "DATA/menu.jpg",
            "DATA/Rebel logo.jpg",
            "DATA/TB/English/btomb_m12.jpg",
            "DATA/TB/English/btomb_m12_hi.jpg",
            "DATA/TB/English/chaos_m17_hi.jpg",
            "DATA/TB/English/conTower_m16_hi.jpg",
            "DATA/TB/English/desert_m13_hi.jpg",
            "DATA/TB/English/Ice_m11_hi.jpg",
            "DATA/TB/English/muralisla1_hi.jpg",
            "DATA/TB/English/muralnejev_hi.jpg",
            "DATA/TB/English/muralorc_hi.jpg",
            "DATA/TB/English/orc_m9_hi.jpg",
            "DATA/TB/English/orlok_m10_hi.jpg",
            "DATA/TB/English/palace_m15_hi.jpg",
            "DATA/TB/English/sinTower_m16_hi.jpg",
            "DATA/TB/English/tablillas_hi.jpg",
            "DATA/TB/English/volcano_m14_hi.jpg",
            "DATA/TB/English/Amazon_N/island_m8_hi.jpg",
            "DATA/TB/English/Amazon_N/labyrinth_m6_hi.jpg",
            "DATA/TB/English/Amazon_N/mine_m5_hi.jpg",
            "DATA/TB/English/Amazon_N/orc_m9_hi.jpg",
            "DATA/TB/English/Amazon_N/ruins_m4_hi.jpg",
            "DATA/TB/English/Amazon_N/tomb_m7_hi.jpg",
            "DATA/TB/English/Barbarian_N/barb_m1_hi.jpg",
            "DATA/TB/English/Barbarian_N/island_m8_hi.jpg",
            "DATA/TB/English/Barbarian_N/labyrinth_m6_hi.jpg",
            "DATA/TB/English/Barbarian_N/mine_m5_hi.jpg",
            "DATA/TB/English/Barbarian_N/tomb_m7_hi.jpg",
            "DATA/TB/English/Dwarf_N/dwarf_m3_hi.jpg",
            "DATA/TB/English/Dwarf_N/island_m8_hi.jpg",
            "DATA/TB/English/Dwarf_N/labyrinth_m6_hi.jpg",
            "DATA/TB/English/Dwarf_N/mine_m5_hi.jpg",
            "DATA/TB/English/Dwarf_N/tomb_m7_hi.jpg",
            "DATA/TB/English/Items/plantillaGitems.jpg",
            "DATA/TB/English/Items/plantillaGitems_hi.jpg",
            "DATA/TB/English/Knight_N/island_m8_hi.jpg",
            "DATA/TB/English/Knight_N/labyrinth_m6_hi.jpg",
            "DATA/TB/English/Knight_N/mine_m5_hi.jpg",
            "DATA/TB/English/Knight_N/orc_m9_hi.jpg",
            "DATA/TB/English/Knight_N/ragnar_m2_hi.jpg",
            "DATA/TB/English/Knight_N/tomb_m7_hi.jpg",
            # .png
            "DATA/electricPrtl_hi.png",
            "DATA/espiritu_hi.png",
            "DATA/Estrellita2_hi.png",
            "DATA/Estrellita_hi.png",
            "DATA/FirePrtl_hi.png",
            "DATA/Flare magico 128_hi.png",
            "DATA/Flare magico 256_hi.png",
            "DATA/GenericPrtl2_hi.png",
            "DATA/GenericPrtl_hi.png",
            "DATA/Glow_hi.png",
            "DATA/KeyGlow_hi.png",
            "DATA/menu_wide.png",
            "DATA/prueba flare magico 128_hi.png",
            "DATA/prueba flare magico 256_hi.png",
            "DATA/Salpicadura_hi.png",
            "DATA/SmokePrtl3_hi.png",
            "DATA/SmokePrtl_hi.png",
            "DATA/SunFlare_hi.png",
            "DATA/tb_0_hi.png",
            "DATA/tb_1_hi.png",
            "DATA/Tornado_hi.png",
            "DATA/Water2_hi.png",
            "DATA/Water_hi.png",
            "DATA/Icons/chaos_hi.png",
            "DATA/Icons/Glm_cl_hi.png",
            "DATA/Icons/Glm_lv_hi.png",
            "DATA/Icons/Glm_mt_hi.png",
            "DATA/Icons/Glm_st_hi.png",
            "DATA/Icons/Icono Darklord_hi.png",
            "DATA/Icons/Knight zombie_hi.png",
            "DATA/Icons/Ldemon_hi.png",
            "DATA/Icons/lich_hi.png",
            "DATA/Icons/skull_hi.png",
            # .bmp
            "DATA/LogoRebel256.bmp",
            "DATA/Rebel Logo.bmp",
            "DATA/Water.bmp",
            "DATA/Water2.bmp",
        ]

    return ret
